const SET_SINGLE_PROJECT = 'singleProject/SET_SINGLE_PROJECT';
const UPDATE_SINGLE_PROJECT = 'singleProject/UPDATE_SINGLE_PROJECT';

export const types = {
  SET_SINGLE_PROJECT,
  UPDATE_SINGLE_PROJECT,
};
